[mysql_serve]
host = "localhost"
port = "3307"
username = "root"
password = "root"
database = "Rust2023"

[redis_serve]
host = "localhost"

[input]
json_file = "./resource/data.json"
xml_file = "./resource/data.xml"

[output]
file = "./db"